package com.ironvellum.app.ui.components

// GENERATED by tools/crest_art/build.py from tools/crest_art/marks.txt. Do not edit by hand.
// Flat line art in a 100 x 100 box, with a translucent wash and Void's dark negative space.

/**
 * One shape of a crest mark: an absolute path [d] in the 100 x 100 box, its [wash] (the fill's alpha, 0 for
 * none, at most [MAX_WASH]), its stroke alpha, width and caps, and an optional dash.
 */
internal class CrestShape(
    val d: String,
    val wash: Float,
    val strokeAlpha: Float,
    val width: Float,
    val roundCap: Boolean,
    val roundJoin: Boolean,
    val dash: FloatArray? = null,
    val darkGround: Boolean = false,
)

internal const val MAX_WASH = 0.18f

/** Every crest mark by catalogue id. */
internal val CREST_SHAPES: Map<String, List<CrestShape>> = mapOf(
    "iron" to listOf(
        CrestShape("M50 10L84 22V50C84 72 68 86 50 92C32 86 16 72 16 50V22Z", 0f, 1f, 3f, true, true),
        CrestShape("M26 30V50C26 66 38 77 50 82C62 77 74 66 74 50V30", 0f, 0.4f, 3f, true, true),
        CrestShape("M50 30L64 50L50 70L36 50Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M30 38L50 24L70 38", 0f, 0.6f, 3f, true, true),
    ),
    "bronze" to listOf(
        CrestShape("M48 88C26 78 18 56 26 30M52 88C74 78 82 56 74 30", 0f, 1f, 3f, true, true),
        CrestShape("M27 68C14 65 12 55 14 47C25 50 30 57 27 68Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 48C15 42 16 29 20 23C29 32 29 40 24 48Z", 0f, 1f, 3f, true, true),
        CrestShape("M29 31C23 19 30 11 36 9C40 20 37 27 29 31Z", 0f, 1f, 3f, true, true),
        CrestShape("M73 68C86 65 88 55 86 47C75 50 70 57 73 68Z", 0f, 1f, 3f, true, true),
        CrestShape("M76 48C85 42 84 29 80 23C71 32 71 40 76 48Z", 0f, 1f, 3f, true, true),
        CrestShape("M71 31C77 19 70 11 64 9C60 20 63 27 71 31Z", 0f, 1f, 3f, true, true),
        CrestShape("M41 86L50 81L59 86", 0f, 1f, 3f, true, true),
    ),
    "silver" to listOf(
        CrestShape("M57 11C43 8 33 18 37 28C40 35 46 38 54 35C44 30 43 18 57 11Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 88L71 48M76 88L54 69M46 62L29 48", 0f, 1f, 3f, true, true),
        CrestShape("M66 46L80 37L76 51ZM34 46L20 37L24 51Z", 0f, 1f, 3f, true, true),
    ),
    "gold" to listOf(
        CrestShape("M28 70A22 22 0 0 1 72 70", 0.12f, 1f, 4f, true, true),
        CrestShape("M80 70H96M76 55L89.8 47M65 44L73 30.2M50 40V24M35 44L27 30.2M24 55L10.2 47M20 70H4", 0f, 1f, 4f, true, true),
        CrestShape("M14 80H86", 0f, 1f, 3f, true, true),
    ),
    "jade" to listOf(
        CrestShape("M68 20C40 12 26 32 44 46C62 58 74 68 52 82C42 88 30 84 26 76", 0f, 1f, 3.2f, true, true),
        CrestShape("M67 21A3 3 0 1 0 73 21A3 3 0 1 0 67 21Z", 0f, 1f, 3.2f, true, true),
        CrestShape("M52 34C66 42 66 58 52 70C38 58 38 42 52 34Z", 0.12f, 1f, 3.2f, true, true),
        CrestShape("M52 36V68", 0f, 1f, 2f, true, true),
    ),
    "crimson" to listOf(
        CrestShape("M32 84L30 65C21 59 18 50 23 42L29 38L36 44V29C36 22 45 21 49 26C52 19 61 21 63 27C68 23 76 26 76 33V51C76 60 69 65 66 68L65 84Z", 0f, 1f, 3f, true, true),
        CrestShape("M29 38L46 48Q51 52 46 58L39 61", 0f, 1f, 3f, true, true),
        CrestShape("M49 26V37M63 27V39", 0f, 1f, 3f, true, true),
        CrestShape("M31 74H66", 0f, 1f, 3f, true, true),
    ),
    "obsidian" to listOf(
        CrestShape("M50 9L74 30L80 67L50 91L20 67L27 30Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 9L42 36L50 91", 0f, 1f, 3f, true, true),
        CrestShape("M42 36L74 30M42 36L20 67", 0f, 1f, 3f, true, true),
    ),
    "verdant" to listOf(
        CrestShape("M50 88V51", 0f, 1f, 3f, true, true),
        CrestShape("M50 61C24 67 15 53 21 39C15 26 31 18 41 23C44 10 62 10 66 23C81 20 91 34 81 44C88 59 70 70 50 61Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 61L35 44M50 54L63 37", 0f, 1f, 3f, true, true),
        CrestShape("M35 88Q50 77 65 88", 0f, 1f, 3f, true, true),
    ),
    "ember" to listOf(
        CrestShape("M50 8C58 26 76 36 74 58C73 74 62 86 50 86C38 86 27 74 26 58C25 44 36 38 40 28C44 34 46 38 48 38C52 28 50 18 50 8Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 50C56 58 62 64 58 72C56 78 52 80 50 80C46 80 42 76 42 70C42 62 48 58 50 50Z", 0f, 1f, 3f, true, true),
        CrestShape("M30 92H70", 0f, 1f, 3f, true, true),
    ),
    "vellum" to listOf(
        CrestShape("M23 14H77A5 5 0 0 1 82 19V20A5 5 0 0 1 77 25H23A5 5 0 0 1 18 20V19A5 5 0 0 1 23 14Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M23 75H77A5 5 0 0 1 82 80V81A5 5 0 0 1 77 86H23A5 5 0 0 1 18 81V80A5 5 0 0 1 23 75Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M26 25V75M74 25V75", 0f, 1f, 3f, true, true),
        CrestShape("M36 38H64M36 48H64M36 58H52", 0f, 0.7f, 3f, true, true),
        CrestShape("M57 62A7 7 0 1 0 71 62A7 7 0 1 0 57 62Z", 0.12f, 1f, 3f, true, true),
    ),
    "sovereign" to listOf(
        CrestShape("M18 72L11 34L34 52L50 22L66 52L89 34L82 72Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M18 82H82", 0f, 1f, 3f, true, true),
        CrestShape("M7 30A4 4 0 1 0 15 30A4 4 0 1 0 7 30Z", 0f, 1f, 3f, true, true),
        CrestShape("M46 17A4 4 0 1 0 54 17A4 4 0 1 0 46 17Z", 0f, 1f, 3f, true, true),
        CrestShape("M85 30A4 4 0 1 0 93 30A4 4 0 1 0 85 30Z", 0f, 1f, 3f, true, true),
    ),
    "ironvellum" to listOf(
        CrestShape("M50 34C40 28 26 28 14 32V78C26 74 40 74 50 80C60 74 74 74 86 78V32C74 28 60 28 50 34Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 34V80", 0f, 1f, 3f, true, true),
        CrestShape("M50 6L59 15L50 24L41 15Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 44C30 42 36 42 42 44M24 55C30 53 36 53 42 55M58 44C64 42 70 42 76 44M58 55C64 53 70 53 76 55", 0f, 0.65f, 3f, true, true),
    ),
    "watchfire" to listOf(
        CrestShape("M50 10C57 24 67 30 63 44C61 50 57 54 50 54C43 54 39 50 39 44C39 36 47 32 50 10Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 58H76C76 72 65 80 50 80C35 80 24 72 24 58Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M38 78L31 93M62 78L69 93M50 80V93", 0f, 1f, 3f, true, true),
    ),
    "anvil" to listOf(
        CrestShape("M10 34H86L78 48H62V58L70 66V78H30V66L38 58V48H30C20 48 14 42 10 34Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 88H76", 0f, 1f, 3f, true, true),
    ),
    "sage" to listOf(
        CrestShape("M50 85V39C50 26 57 17 66 12C69 28 62 39 50 43", 0f, 1f, 3f, true, true),
        CrestShape("M50 59C32 60 23 50 22 35C38 34 49 45 50 59", 0f, 1f, 3f, true, true),
        CrestShape("M50 73C67 72 77 62 78 48C63 47 52 59 50 73", 0f, 1f, 3f, true, true),
        CrestShape("M38 87Q50 80 62 87", 0f, 1f, 3f, true, true),
    ),
    "dawnroad" to listOf(
        CrestShape("M30 56A20 20 0 0 1 70 56Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 18V28M27 28L33 35M73 28L67 35M13 46L22 48M87 46L78 48", 0f, 1f, 3f, true, true),
        CrestShape("M8 56H92", 0f, 1f, 3f, true, true),
        CrestShape("M44 58L22 92M56 58L78 92", 0f, 1f, 3f, true, true),
        CrestShape("M50 64V70M50 77V84", 0f, 1f, 3f, true, true),
    ),
    "throne" to listOf(
        CrestShape("M31 55V32Q31 19 42 15L50 9L58 15Q69 19 69 32V55", 0f, 1f, 3f, true, true),
        CrestShape("M23 44V64H77V44", 0f, 1f, 3f, true, true),
        CrestShape("M23 44Q30 38 35 44M65 44Q71 38 77 44", 0f, 1f, 3f, true, true),
        CrestShape("M28 64L25 86H36L39 73H61L64 86H75L72 64", 0f, 1f, 3f, true, true),
        CrestShape("M39 55H61", 0f, 1f, 3f, true, true),
        CrestShape("M50 25L56 33L50 41L44 33Z", 0f, 1f, 3f, true, true),
    ),
    "marathon" to listOf(
        CrestShape("M29 86V16", 0f, 1f, 3f, true, true),
        CrestShape("M30 22C44 13 56 31 75 23V48C57 57 45 39 30 48", 0f, 1f, 3f, true, true),
        CrestShape("M18 86H40", 0f, 1f, 3f, true, true),
        CrestShape("M48 82C67 78 60 69 79 63", 0f, 1f, 3f, true, true),
    ),
    "ironhold" to listOf(
        CrestShape("M22 90V34H33V24H44V34H56V24H67V34H78V90Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M42 90V70A8 8 0 0 1 58 70V90", 0f, 1f, 3f, true, true),
        CrestShape("M47 48H53V56H47Z", 0f, 1f, 3f, true, true),
    ),
    "bellwarden" to listOf(
        CrestShape("M46 13A4 4 0 1 0 54 13A4 4 0 1 0 46 13Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 17C34 17 28 36 28 50C28 64 20 70 17 76H83C80 70 72 64 72 50C72 36 66 17 50 17Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M42 83A8 8 0 0 0 58 83", 0f, 1f, 3f, true, true),
    ),
    "masterwright" to listOf(
        CrestShape("M17 21H53V37H17Z", 0f, 1f, 3f, true, true),
        CrestShape("M31 37V82H39V37", 0f, 1f, 3f, true, true),
        CrestShape("M67 17H77V66L72 83L67 66Z", 0f, 1f, 3f, true, true),
    ),
    "hearthgate" to listOf(
        CrestShape("M19 88V47C19 27 32 14 50 14C68 14 81 27 81 47V88", 0f, 1f, 3f, true, true),
        CrestShape("M29 88V48C29 34 38 25 50 25C62 25 71 34 71 48V88", 0f, 1f, 3f, true, true),
        CrestShape("M50 25V40", 0f, 1f, 3f, true, true),
        CrestShape("M40 47L44 40H56L60 47L57 65H43Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 50Q44 57 50 60Q56 57 50 50", 0f, 1f, 3f, true, true),
        CrestShape("M14 88H86", 0f, 1f, 3f, true, true),
    ),
    "aurora" to listOf(
        CrestShape("M13 53C26 58 32 21 48 29S68 58 87 24L87 48C68 82 61 53 48 53S26 82 13 77Z", 0.18f, 0f, 1f, false, false),
        CrestShape("M13 53C26 58 32 21 48 29S68 58 87 24", 0f, 1f, 4f, true, true),
        CrestShape("M21 53V70M32 38V63M44 28V52M56 34V62M68 43V68M80 36V60", 0f, 1f, 3.2f, true, true),
    ),
    "void" to listOf(
        CrestShape("M22 50A28 28 0 1 0 78 50A28 28 0 1 0 22 50Z", 0f, 0f, 1f, false, false, darkGround = true),
        CrestShape("M28 70C16 58 17 39 29 27C43 13 65 16 77 31", 0f, 1f, 5f, true, false),
        CrestShape("M72 30C84 42 83 61 71 73C57 87 35 84 23 69", 0f, 0.55f, 3f, true, false),
    ),
    "masterwork" to listOf(
        CrestShape("M50 9L59 33L82 18L68 42L91 50L68 58L82 82L59 67L50 91L41 67L18 82L32 58L9 50L32 42L18 18L41 33Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 36L61 50L50 64L39 50Z", 0f, 1f, 3f, true, true),
    ),
    "ledger" to listOf(
        CrestShape("M24 12H72A4 4 0 0 1 76 16V84H28A4 4 0 0 1 24 80Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 80A4 4 0 0 1 28 76H76", 0f, 1f, 3f, true, true),
        CrestShape("M34 32H64M34 44H64M34 56H54", 0f, 0.7f, 3f, true, true),
        CrestShape("M62 12V30L67 26L72 30V12", 0f, 1f, 3f, true, true),
    ),
    "margin" to listOf(
        CrestShape("M25 13H75V87H25Z", 0f, 1f, 3f, true, true),
        CrestShape("M37 13V87", 0f, 1f, 3f, true, true),
        CrestShape("M48 65C44 47 56 29 68 25C73 39 63 55 48 65Z", 0f, 1f, 3f, true, true),
        CrestShape("M44 76L62 39", 0f, 1f, 3f, true, true),
    ),
    "ashenking" to listOf(
        CrestShape("M16 76L11 40L34 56L50 26L66 56L89 40L84 76Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 26L45 46L56 56L49 76", 0f, 0.6f, 3f, true, true),
        CrestShape("M14 86H86", 0f, 1f, 3f, true, true),
        CrestShape("M28 16A2 2 0 1 0 32 16A2 2 0 1 0 28 16Z", 0f, 1f, 3f, true, true),
        CrestShape("M70 12A2 2 0 1 0 74 12A2 2 0 1 0 70 12Z", 0f, 1f, 3f, true, true),
        CrestShape("M50.4 8A1.6 1.6 0 1 0 53.6 8A1.6 1.6 0 1 0 50.4 8Z", 0f, 1f, 3f, true, true),
    ),
)
