package com.ironvellum.app.ui.components

import androidx.annotation.DrawableRes
import androidx.compose.foundation.Image
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import com.ironvellum.app.R

/**
 * The drawn heraldic mark for a crest frame.
 *
 * These replace the procedural emblem that composed a crown/chevron/orbit/rune
 * from the frame's id. That generator could keep ten marks distinct, but not
 * make any of them look drawn — the owner's verdict on it was that a generated
 * heraldic mark is below the bar for the one cosmetic the game sells.
 *
 * Each mark is brushed ink on transparency at 256px, generated by
 * `tools/art_batches/crests.txt` and committed under
 * `tools/art_batches/drawn/`. They are NOT tinted: a single-colour tint flattens
 * the brush into a silhouette, and the plate under them already carries the
 * frame's palette.
 */
@DrawableRes
fun crestArt(frameId: String): Int? = when (frameId) {
    "iron" -> R.drawable.art_crest_iron
    "bronze" -> R.drawable.art_crest_bronze
    "silver" -> R.drawable.art_crest_silver
    "gold" -> R.drawable.art_crest_gold
    "jade" -> R.drawable.art_crest_jade
    "crimson" -> R.drawable.art_crest_crimson
    "obsidian" -> R.drawable.art_crest_obsidian
    "aurora" -> R.drawable.art_crest_aurora
    "void" -> R.drawable.art_crest_void
    "masterwork" -> R.drawable.art_crest_masterwork
    // An id with no art draws nothing rather than a stand-in: the catalogue and
    // this map are checked against each other by CrestArtCoverageTest, so a new
    // frame fails a test instead of shipping a hole.
    else -> null
}

/** One drawn crest mark, sized by the caller. Draws nothing for an unknown id. */
@Composable
fun CrestMark(frameId: String, modifier: Modifier = Modifier) {
    val art = crestArt(frameId) ?: return
    Image(
        painter = painterResource(art),
        contentDescription = null,
        contentScale = ContentScale.Fit,
        modifier = modifier,
    )
}
