package com.ironvellum.app.ui.components

// GENERATED by tools/crest_art/build.py from tools/crest_art/marks.txt. Do not edit by hand.
// Line art in a 100 x 100 box: every shape is a stroke with, at most, a 12% wash. Never a solid fill.

/**
 * One shape of a crest mark: an absolute path [d] in the 100 x 100 box, its [wash] (the fill's alpha, 0 for
 * none, at most [MAX_WASH]), its stroke alpha, width and caps, and an optional dash.
 */
internal class CrestShape(
    val d: String,
    val wash: Float,
    val strokeAlpha: Float,
    val width: Float,
    val roundCap: Boolean,
    val roundJoin: Boolean,
    val dash: FloatArray? = null,
)

internal const val MAX_WASH = 0.12f

/** Every crest mark by catalogue id. */
internal val CREST_SHAPES: Map<String, List<CrestShape>> = mapOf(
    "iron" to listOf(
        CrestShape("M50 10L84 22V50C84 72 68 86 50 92C32 86 16 72 16 50V22Z", 0f, 1f, 3f, true, true),
        CrestShape("M26 30V50C26 66 38 77 50 82C62 77 74 66 74 50V30", 0f, 0.4f, 3f, true, true),
        CrestShape("M50 30L64 50L50 70L36 50Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M30 38L50 24L70 38", 0f, 0.6f, 3f, true, true),
    ),
    "bronze" to listOf(
        CrestShape("M26.94 69.43A4 9 40 1 0 33.06 74.57A4 9 40 1 0 26.94 69.43Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M19.14 56.96A4 9 15 1 0 26.86 59.04A4 9 15 1 0 19.14 56.96Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M18.04 43.56A4 9 -8 1 0 25.96 42.44A4 9 -8 1 0 18.04 43.56Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M24.61 31.12A4 9 -32 1 0 31.39 26.88A4 9 -32 1 0 24.61 31.12Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M66.94 74.57A4 9 -40 1 0 73.06 69.43A4 9 -40 1 0 66.94 74.57Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M73.14 59.04A4 9 -15 1 0 80.86 56.96A4 9 -15 1 0 73.14 59.04Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M74.04 42.44A4 9 8 1 0 81.96 43.56A4 9 8 1 0 74.04 42.44Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M68.61 26.88A4 9 32 1 0 75.39 31.12A4 9 32 1 0 68.61 26.88Z", 0.12f, 1f, 2.4f, true, false),
        CrestShape("M36 52H64", 0f, 1f, 6f, true, false),
        CrestShape("M50 88L40 82M50 88L60 82", 0f, 1f, 2.4f, true, false),
    ),
    "silver" to listOf(
        CrestShape("M62 16A21 21 0 1 0 62 52A16 16 0 0 1 62 16Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M22 92L72 44M78 92L28 44", 0f, 1f, 3f, true, true),
        CrestShape("M76 38L64 42L72 52Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 38L36 42L28 52Z", 0.12f, 1f, 3f, true, true),
    ),
    "gold" to listOf(
        CrestShape("M28 70A22 22 0 0 1 72 70", 0.12f, 1f, 4f, true, true),
        CrestShape("M80 70H96M76 55L89.8 47M65 44L73 30.2M50 40V24M35 44L27 30.2M24 55L10.2 47M20 70H4", 0f, 1f, 4f, true, true),
        CrestShape("M14 80H86", 0f, 1f, 3f, true, true),
    ),
    "jade" to listOf(
        CrestShape("M68 20C40 12 26 32 44 46C62 58 74 68 52 82C42 88 30 84 26 76", 0f, 1f, 3.2f, true, true),
        CrestShape("M67 21A3 3 0 1 0 73 21A3 3 0 1 0 67 21Z", 0f, 1f, 3.2f, true, true),
        CrestShape("M52 34C66 42 66 58 52 70C38 58 38 42 52 34Z", 0.12f, 1f, 3.2f, true, true),
        CrestShape("M52 36V68", 0f, 1f, 2f, true, true),
    ),
    "crimson" to listOf(
        CrestShape("M34 20H66A6 6 0 0 1 72 26V46A10 10 0 0 1 62 56H38A10 10 0 0 1 28 46V26A6 6 0 0 1 34 20Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M44 20V36M56 20V36M28 40H18", 0f, 1f, 3f, true, true),
        CrestShape("M36 58H64V88H36Z", 0.08f, 1f, 3f, true, true),
    ),
    "obsidian" to listOf(
        CrestShape("M50 8L84 30V70L50 92L16 70V30Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 8L64 50L50 92L36 50Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M16 30L64 50L16 70M84 30L36 50L84 70", 0f, 0.55f, 3f, true, true),
    ),
    "verdant" to listOf(
        CrestShape("M33 32A17 17 0 1 0 67 32A17 17 0 1 0 33 32Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M21 48A12 12 0 1 0 45 48A12 12 0 1 0 21 48Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M55 48A12 12 0 1 0 79 48A12 12 0 1 0 55 48Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 56V88", 0f, 1f, 3f, true, true),
        CrestShape("M50 74L38 86M50 74L62 86", 0f, 1f, 3f, true, true),
        CrestShape("M50 66L42 60M50 66L58 60", 0f, 0.6f, 3f, true, true),
    ),
    "ember" to listOf(
        CrestShape("M50 8C58 26 76 36 74 58C73 74 62 86 50 86C38 86 27 74 26 58C25 44 36 38 40 28C44 34 46 38 48 38C52 28 50 18 50 8Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 50C56 58 62 64 58 72C56 78 52 80 50 80C46 80 42 76 42 70C42 62 48 58 50 50Z", 0f, 1f, 3f, true, true),
        CrestShape("M30 92H70", 0f, 1f, 3f, true, true),
    ),
    "vellum" to listOf(
        CrestShape("M23 14H77A5 5 0 0 1 82 19V20A5 5 0 0 1 77 25H23A5 5 0 0 1 18 20V19A5 5 0 0 1 23 14Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M23 75H77A5 5 0 0 1 82 80V81A5 5 0 0 1 77 86H23A5 5 0 0 1 18 81V80A5 5 0 0 1 23 75Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M26 25V75M74 25V75", 0f, 1f, 3f, true, true),
        CrestShape("M36 38H64M36 48H64M36 58H52", 0f, 0.7f, 3f, true, true),
        CrestShape("M57 62A7 7 0 1 0 71 62A7 7 0 1 0 57 62Z", 0.12f, 1f, 3f, true, true),
    ),
    "sovereign" to listOf(
        CrestShape("M18 72L11 34L34 52L50 22L66 52L89 34L82 72Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M18 82H82", 0f, 1f, 3f, true, true),
        CrestShape("M7 30A4 4 0 1 0 15 30A4 4 0 1 0 7 30Z", 0f, 1f, 3f, true, true),
        CrestShape("M46 17A4 4 0 1 0 54 17A4 4 0 1 0 46 17Z", 0f, 1f, 3f, true, true),
        CrestShape("M85 30A4 4 0 1 0 93 30A4 4 0 1 0 85 30Z", 0f, 1f, 3f, true, true),
    ),
    "ironvellum" to listOf(
        CrestShape("M50 34C40 28 26 28 14 32V78C26 74 40 74 50 80C60 74 74 74 86 78V32C74 28 60 28 50 34Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 34V80", 0f, 1f, 3f, true, true),
        CrestShape("M50 6L59 15L50 24L41 15Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 44C30 42 36 42 42 44M24 55C30 53 36 53 42 55M58 44C64 42 70 42 76 44M58 55C64 53 70 53 76 55", 0f, 0.65f, 3f, true, true),
    ),
    "watchfire" to listOf(
        CrestShape("M50 10C57 24 67 30 63 44C61 50 57 54 50 54C43 54 39 50 39 44C39 36 47 32 50 10Z", 0f, 1f, 3f, true, true),
        CrestShape("M24 58H76C76 72 65 80 50 80C35 80 24 72 24 58Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M38 78L31 93M62 78L69 93M50 80V93", 0f, 1f, 3f, true, true),
    ),
    "anvil" to listOf(
        CrestShape("M10 34H86L78 48H62V58L70 66V78H30V66L38 58V48H30C20 48 14 42 10 34Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 88H76", 0f, 1f, 3f, true, true),
    ),
    "sage" to listOf(
        CrestShape("M50 70V28M50 52L30 36M50 52L70 36", 0f, 1f, 3f, true, true),
        CrestShape("M43 76A7 7 0 1 0 57 76A7 7 0 1 0 43 76Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M43 20A7 7 0 1 0 57 20A7 7 0 1 0 43 20Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M21 32A7 7 0 1 0 35 32A7 7 0 1 0 21 32Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M65 32A7 7 0 1 0 79 32A7 7 0 1 0 65 32Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M26 92H74", 0f, 0.6f, 3f, true, true),
    ),
    "dawnroad" to listOf(
        CrestShape("M30 56A20 20 0 0 1 70 56Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 18V28M27 28L33 35M73 28L67 35M13 46L22 48M87 46L78 48", 0f, 1f, 3f, true, true),
        CrestShape("M8 56H92", 0f, 1f, 3f, true, true),
        CrestShape("M44 58L22 92M56 58L78 92", 0f, 1f, 3f, true, true),
        CrestShape("M50 64V70M50 77V84", 0f, 1f, 3f, true, true),
    ),
    "throne" to listOf(
        CrestShape("M32 10H68V52H32Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 52H76V66H24Z", 0f, 1f, 3f, true, true),
        CrestShape("M30 66V90M70 66V90", 0f, 1f, 3f, true, true),
        CrestShape("M44 28A6 6 0 1 0 56 28A6 6 0 1 0 44 28Z", 0f, 1f, 3f, true, true),
    ),
    "marathon" to listOf(
        CrestShape("M30 10V90", 0f, 1f, 3f, true, true),
        CrestShape("M30 14L74 30L30 48Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M14 90H70", 0f, 1f, 3f, true, true),
        CrestShape("M44 72C54 66 68 66 82 72", 0f, 0.6f, 3f, true, true),
    ),
    "ironhold" to listOf(
        CrestShape("M22 90V34H33V24H44V34H56V24H67V34H78V90Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M42 90V70A8 8 0 0 1 58 70V90", 0f, 1f, 3f, true, true),
        CrestShape("M47 48H53V56H47Z", 0f, 1f, 3f, true, true),
    ),
    "bellwarden" to listOf(
        CrestShape("M46 13A4 4 0 1 0 54 13A4 4 0 1 0 46 13Z", 0f, 1f, 3f, true, true),
        CrestShape("M50 17C34 17 28 36 28 50C28 64 20 70 17 76H83C80 70 72 64 72 50C72 36 66 17 50 17Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M42 83A8 8 0 0 0 58 83", 0f, 1f, 3f, true, true),
    ),
    "masterwright" to listOf(
        CrestShape("M11.73 36.75L46.4 9.66L58.72 25.42L24.04 52.51Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M41.38 38.97L74.63 81.52", 0f, 1f, 3f, true, true),
        CrestShape("M70.69 15.4L78.57 21.56L47.78 60.96L36.46 67.34L39.9 54.8Z", 0.12f, 1f, 3f, true, true),
    ),
    "hearthgate" to listOf(
        CrestShape("M20 90V46A30 30 0 0 1 80 46V90", 0f, 1f, 3f, true, true),
        CrestShape("M33 90V50A17 17 0 0 1 67 50V90", 0f, 0.5f, 3f, true, true),
        CrestShape("M50 38V46", 0f, 1f, 3f, true, true),
        CrestShape("M43 46H57V64H43Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M46 70H54", 0f, 1f, 3f, true, true),
        CrestShape("M14 90H86", 0f, 1f, 3f, true, true),
    ),
    "aurora" to listOf(
        CrestShape("M12 72C28 28 72 28 88 72", 0f, 1f, 3.2f, true, false),
        CrestShape("M24 76C38 44 62 44 76 76", 0f, 0.7f, 3.2f, true, false),
        CrestShape("M36 80C44 60 56 60 64 80", 0f, 0.45f, 3.2f, true, false),
        CrestShape("M24 22A2 2 0 1 0 28 22A2 2 0 1 0 24 22Z", 0f, 1f, 1.6f, true, false),
        CrestShape("M71.6 16A2.4 2.4 0 1 0 76.4 16A2.4 2.4 0 1 0 71.6 16Z", 0f, 1f, 1.6f, true, false),
        CrestShape("M50.4 12A1.6 1.6 0 1 0 53.6 12A1.6 1.6 0 1 0 50.4 12Z", 0f, 1f, 1.6f, true, false),
    ),
    "void" to listOf(
        CrestShape("M16 50A34 34 0 1 0 84 50A34 34 0 1 0 16 50Z", 0f, 1f, 3f, true, false),
        CrestShape("M30 50A20 20 0 1 0 70 50A20 20 0 1 0 30 50Z", 0f, 0.7f, 3f, true, false, dash = floatArrayOf(4f, 6f)),
        CrestShape("M44 50A6 6 0 1 0 56 50A6 6 0 1 0 44 50Z", 0f, 1f, 3f, true, false),
        CrestShape("M50 8V20M50 80V92M8 50H20M80 50H92", 0f, 0.5f, 3f, true, false),
    ),
    "masterwork" to listOf(
        CrestShape("M50 8L59 30L82 18L70 41L92 50L70 59L82 82L59 70L50 92L41 70L18 82L30 59L8 50L30 41L18 18L41 30Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M35 50A15 15 0 1 0 65 50A15 15 0 1 0 35 50Z", 0f, 1f, 3f, true, true),
        CrestShape("M45 50A5 5 0 1 0 55 50A5 5 0 1 0 45 50Z", 0f, 1f, 3f, true, true),
    ),
    "ledger" to listOf(
        CrestShape("M24 12H72A4 4 0 0 1 76 16V84H28A4 4 0 0 1 24 80Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M24 80A4 4 0 0 1 28 76H76", 0f, 1f, 3f, true, true),
        CrestShape("M34 32H64M34 44H64M34 56H54", 0f, 0.7f, 3f, true, true),
        CrestShape("M62 12V30L67 26L72 30V12", 0f, 1f, 3f, true, true),
    ),
    "margin" to listOf(
        CrestShape("M26 12H74V88H26Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M38 12V88", 0f, 1f, 3f, true, true),
        CrestShape("M26 28H38M26 40H38M26 52H38M26 64H38M26 76H38", 0f, 0.6f, 3f, true, true),
        CrestShape("M47 32H66M47 46H66M47 60H58", 0f, 0.7f, 3f, true, true),
    ),
    "ashenking" to listOf(
        CrestShape("M16 76L11 40L34 56L50 26L66 56L89 40L84 76Z", 0.12f, 1f, 3f, true, true),
        CrestShape("M50 26L45 46L56 56L49 76", 0f, 0.6f, 3f, true, true),
        CrestShape("M14 86H86", 0f, 1f, 3f, true, true),
        CrestShape("M28 16A2 2 0 1 0 32 16A2 2 0 1 0 28 16Z", 0f, 1f, 3f, true, true),
        CrestShape("M70 12A2 2 0 1 0 74 12A2 2 0 1 0 70 12Z", 0f, 1f, 3f, true, true),
        CrestShape("M50.4 8A1.6 1.6 0 1 0 53.6 8A1.6 1.6 0 1 0 50.4 8Z", 0f, 1f, 3f, true, true),
    ),
)
