package com.ironvellum.app.ui.program

import com.ironvellum.app.domain.Muscle
import com.ironvellum.app.domain.Muscle.*

/**
 * The shapes of one body as BodyMapShapes (generated by tools/bodymap_import.py) stores them: its outline
 * and, per view, each named part as packed integer pairs. Packed strings, because list literals this
 * size overflow the JVM's 64KB method limit; [BodyFigure] decodes them once.
 */
internal class BodyShapes(
    val outline: String,
    val hairFront: String,
    val hairBack: String,
    val front: Map<String, String>,
    val back: Map<String, String>,
)

/**
 * One muscle region: half of it, in figure space, mirrored across the midline to draw both sides. Figure
 * space is proportioned by height: x runs from the midline (0) outwards in units of the figure's height,
 * y from the crown (0) to the soles (1), so the shapes keep their anatomy at any size. A muscle can have
 * several regions (the quadriceps' three heads); each is one simple polygon.
 */
internal class Region(val muscle: Muscle, val points: List<Pair<Float, Float>>)

internal enum class FigureView { FRONT, BACK }

/**
 * The body a lifter's profile picks: its skin outline and every muscle region, front and back.
 *
 * [hair] is decoration on the head, in the darkest ink: it is never a [Region], so it is never coloured
 * and never tapped. [outline] is the right half only, an open chain from the crown to the crotch with both ends on the
 * midline; [fullOutline] mirrors it into the closed silhouette. [regionsOf] is the lookup by muscle that
 * tapping a muscle on the figure will want.
 */
internal class BodyFigure(shapes: BodyShapes) {
    val outline: List<Pair<Float, Float>> = decodePoints(shapes.outline)
    val front: List<Region> = regions(shapes.front, FRONT_PARTS)
    val back: List<Region> = regions(shapes.back, BACK_PARTS)

    val fullOutline: List<Pair<Float, Float>> =
        outline + outline.subList(1, outline.lastIndex).asReversed().map { (x, y) -> -x to y }

    /** Half the widest the body gets, in figure units: the hands, held away from the hips. */
    val halfWidth: Float = outline.maxOf { it.first }

    private val hairFront: List<List<Pair<Float, Float>>> = decodePieces(shapes.hairFront)
    private val hairBack: List<List<Pair<Float, Float>>> = decodePieces(shapes.hairBack)

    /** The hair on the head in [view], as right-half polygons to mirror. */
    fun hair(view: FigureView): List<List<Pair<Float, Float>>> = if (view == FigureView.FRONT) hairFront else hairBack

    /** Every muscle either view can colour. */
    val drawn: Set<Muscle> = (front + back).map { it.muscle }.toSet()

    fun regions(view: FigureView): List<Region> = if (view == FigureView.FRONT) front else back

    private val byMuscle: Map<FigureView, Map<Muscle, List<Region>>> = mapOf(
        FigureView.FRONT to front.groupBy { it.muscle },
        FigureView.BACK to back.groupBy { it.muscle },
    )

    /** Every region of [muscle] on [view]; empty when that view does not show it. */
    fun regionsOf(muscle: Muscle, view: FigureView): List<Region> = byMuscle.getValue(view)[muscle].orEmpty()

    private companion object {
        fun regions(parts: Map<String, String>, table: List<Pair<String, Muscle>>): List<Region> {
            val named = table.toMap()
            val unknown = parts.keys - named.keys
            check(unknown.isEmpty()) { "BodyMapShapes has parts BodyFigures does not map: $unknown" }
            return table.flatMap { (key, muscle) ->
                val packed = checkNotNull(parts[key]) { "BodyMapShapes has no part '$key'" }
                decodePieces(packed).map { Region(muscle, it) }
            }
        }

        fun decodePieces(packed: String): List<List<Pair<Float, Float>>> =
            packed.split('|').filter { it.isNotBlank() }.map { decodePoints(it) }

        fun decodePoints(packed: String): List<Pair<Float, Float>> {
            val n = packed.trim().split(' ').map { it.toInt() / UNIT }
            return List(n.size / 2) { n[2 * it] to n[2 * it + 1] }
        }

        const val UNIT = 10000f
    }
}

// What each generated part is. Most are the source's part of that name; the splits (the chest cut along a
// fan from the armpit, the deltoid into its heads, the rib slips out of the obliques, the scapular pieces
// out of upper-back, the medius out of gluteal) and the inlays (rhomboids, brachialis, hip flexors) are
// made by tools/bodymap_import.py, which names them here.
private val FRONT_PARTS = listOf(
    "chest.upper" to UPPER_CHEST,
    "chest.mid" to MID_CHEST,
    "chest.lower" to LOWER_CHEST,
    "serratus" to SERRATUS,
    "obliques" to OBLIQUES,
    "abs" to ABS,
    "hip-flexors" to HIP_FLEXORS,
    "deltoids.front" to FRONT_DELTS,
    "deltoids.side" to SIDE_DELTS,
    "biceps" to BICEPS,
    "brachialis" to BRACHIALIS,
    "triceps" to TRICEPS,
    "forearm" to FOREARMS,
    "trapezius" to TRAPS,
    "neck" to NECK,
    "adductors" to ADDUCTORS,
    "quadriceps" to QUADS,
    "tibialis" to TIBIALIS,
    "calves" to CALVES,
)

private val BACK_PARTS = listOf(
    "trapezius" to TRAPS,
    "rhomboids" to RHOMBOIDS,
    "rotator-cuff" to ROTATOR_CUFF,
    "deltoids.rear" to REAR_DELTS,
    "lats" to LATS,
    "triceps" to TRICEPS,
    "forearm" to FOREARMS,
    "lower-back" to LOWER_BACK,
    "abductors" to ABDUCTORS,
    "gluteal" to GLUTES,
    "hamstring" to HAMSTRINGS,
    "adductors" to ADDUCTORS,
    "calves" to CALVES,
    "neck" to NECK,
)

/** The bodies the figures can draw. */
internal object BodyFigures {
    val MALE: BodyFigure by lazy { BodyFigure(BodyMapShapes.MALE) }
}
